server:
  port: 6699

spring:
  application:
    name: ecui
    tomcat:
      max-active: 200
      max-idle: 100
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=20)

logging:
  path: log
